-- FUNÇÕES STRING NA PRÁTICA

--CONCAT
SELECT ENDERECO_1 || ‘ ’ || BAIRRO || ‘ ’ || CIDADE || ‘ ’ || ESTADO || ‘ - ’ || CEP FROM TABELA_DE_CLIENTES;

--LPAD
SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO,70,’*’) FROM TABELA_DE_PRODUTOS;

--INSTR
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO,’Campo’) FROM TABELA_DE_PRODUTOS;

--REPLACE
SELECT NOME_DE_PRODUTO, REPLACE(NOME_DE_PRODUTO, ‘Litro’, ‘L’) FROM TABELA_DE_PRODUTOS;

SELECT NOME_DE_PRODUTO, REPLACE(REPLACE(NOME_DE_PRODUTO, ‘Litro’, ‘L’), ‘Ls’, ‘L’) FROM TABELA_DE_PRODUTOS;
