-- VIEW

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;

CREATE VIEW VW_SOMA_EMBALAGENS AS
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO 
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM

SELECT EMBALAGEM, SOMA_PRECO FROM VW_SOMA_EMBALAGENS
WHERE SOMA_PRECO >= 80;

/*
Vamos supor que queremos listar todos os produtos cuja embalagem tem a soma maior que 80.

Para isso definimos como consulta SELECT * FROM TABELA_DE_PRODUTOS TP. 
Na linha de baixo definimos INNER JOIN e dentro dele a view VW_SOMA_EMBALAGENS VW. 
Para ligar visão e tabela definimos ON TP.EMBALAGEM = VW.EMBALAGEM. 
Na linha de baixo escrevemos WHERE VW.SOMA_PRECO >= 80.
*/

SELECT * FROM TABELA_DE_PRODUTOS TP
INNER JOIN VW_SOMA_EMBALAGENS VW
ON TP.EMBALAGEM = VW.EMBALAGEM
WHERE VW.SOMA_PRECO >= 80